[package]
name = "aoc20"
version = "0.1.0"
authors = ["Farkal <farkal110@gmail.com>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
regex = "1"
nom = "6"
